Repository NREL/OpenStudio-server, pull requests merged in 2018-03, with the labels that each got.

#296 Documentation Update
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: P1

#299 CONTRIBUTING.md
  CONTRIBUTING.md
Labels: component - documentation

#294 yaml file changes to build server packages for all branches, on Mac a…
  .gitlab-ci.yml
Labels: component - CI

#300 CI REAMDE.md
  ci/README.md
Labels: component - documentation

#303 Update to 2.4.3
  Dockerfile
  server/lib/openstudio_server/version.rb
Labels: P1, PR testing

#287 One-off AMI generation
  ci/gitlab/README.md
  ci/gitlab/build_deploy_ami.py
Labels: PR testing, component - AWS or AMI, component - CI

#315 Create custom AMI's with GitHub ref Gemfiles
  ci/gitlab/README.md
  ci/gitlab/build_deploy_ami.py
Labels: Developer Issue, P1, PR testing, component - AWS or AMI, severity - major bug
