Repository NREL/OpenStudio-server, pull requests merged in 2018-08, with the labels that each got.

#381 Bundle enablement for oscli PR
  .dockerignore
  Dockerfile
  docker/deployment/scripts/aws_osserver_init.sh
  server/app/workers/run_simulate_data_point.rb
  server/config/environments/docker-dev.rb
  server/config/environments/docker-test.rb
  server/config/environments/docker.rb
Labels: blocked by docker openstudio, component - AMI, component - remote

#380 Allow failed init scripts to return zip files with logs.
  server/app/jobs/dj_jobs/run_simulate_data_point.rb
Labels: P2, component - remote

#324 OpenStudio CLI
  .dockerignore
  Dockerfile
  appveyor.yml
  ci/appveyor/setup.cmd
  ci/travis/setup.sh
  ci/travis/test.sh
  docker/deployment/scripts/aws_osserver_init.sh
  server/app/workers/run_simulate_data_point.rb
  server/config/application.rb
  server/config/environments/docker-dev.rb
  server/config/environments/docker-test.rb
  server/config/environments/docker.rb
Labels: P1, component - AMI, component - CI, component - local, manual testing in-progress
