Repository NREL/OpenStudio-server, pull requests merged in 2018-02, with the labels that each got.

#271 Reenable tests
  .travis.yml
  appveyor.yml
  ci/travis/setup.sh
  ci/travis/test.sh
  spec/files/data/db/empty.txt
  spec/files/data/empty.txt
  spec/files/logs/empty.txt
  spec/tests/openstudio_meta_spec.rb
Labels: P1, PR testing, component - CI, severity - blocker

#277 AMI automation script and documentation
  ci/gitlab/README.md
  ci/gitlab/build_deploy_ami.py
  ci/gitlab/requirements.txt
  ci/travis/centos68/Dockerfile
  docker/deployment/openstudio_server_docker_base.json
  docker/deployment/scripts/aws_system_init.sh
Labels: PR testing, component - AWS or AMI, component - CI

#279 Change OpenStudio install path for AppVeyor
  ci/appveyor/setup.cmd
  ci/appveyor/test.ps1
Labels: PR testing
